import 'package:bbbb/constant/app_strings.dart';

Map<String, String> english = {
  "login_to_your_account": "login to your account",
    "you_must_be_logged_in_to_access_this_section": "You must be logged in to access this section",
  "updated_successfully": "updated successfully",
  "something_is_wrong": "something is wrong",
  "registration_successfull": "registration successful",
  "something_is_wrong!": "something is wrong!",
  "please_enter_all_the_field!": "please enter all the fields!",
  "the_password_provided_is_too_weak.": "the password provided is too weak.",
  "the_account_already_exists_for_that_email.": "the account already exists for that email.",
  "please_write_right_email": "please write the right email",
  "error_is": "error is: ",
  "successfully_login": "successfully login",
  "no_user_found_for_that_email.": "no user found for that email.",
  "wrong_password_provided_for_that_user.": "wrong password provided for that user.",
  "log_out": "log out",
  "login_required": "login required",
  "uploaded_successfully.": "uploaded successfully.",
  "owner_name": "owner name",
  "phone_number": "phone number",
  "select_image": "select image",
  "description_must_be_at_least_3_character": "description must be at least 3 characters",
  "cost_must_be_at_least_3_character": "cost must be at least 3 characters",
  "facility_must_be_at_least_3_character": "facility must be at least 3 characters",
  "destination_must_be_at_least_3_character": "destination must be at least 3 characters",
  "login\\nto_your_account": "login to your account",
  "enter_your_email": "enter your email",
  "are_you_sure_to_close_this_app?": "are you sure to close this app?",
  "no_connection": "no connection",
  "please_check_your_internet_connectivity": "please check your internet connectivity",
  "privacy_policy": "privacy policy",
  "please_wait": "please wait",
  "see_more": "see more"
};
