name: bbbb
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: 
  get: 
  get_storage: 
  firebase_auth: 
  firebase_core: 
  cloud_firestore: 
  firebase_storage: 
  fluttertoast: 
  carousel_slider: ^5.0.0
  dots_indicator: 
  image_picker: 
  velocity_x:
    git:
      url: https://github.com/chihuy105/VelocityX.git
      ref: stable
  internet_connection_checker: 
  google_fonts:
  cached_network_image: 
  dropdown_button2: 
  http: ^1.2.1
  html: ^0.15.0
  pay: ^3.1.0
  file_picker: ^5.0.0
  firebase_storage_web: ^3.10.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
