// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gZcWdnKyw_3Xg1ozmDqPtTHiEG-wS3U',
    appId: '1:761714459949:web:5c937371d332e8b6deffa4',
    messagingSenderId: '761714459949',
    projectId: 'traveltovietnam-3270d',
    authDomain: 'traveltovietnam-3270d.firebaseapp.com',
    storageBucket: 'traveltovietnam-3270d.firebasestorage.app',
    measurementId: 'G-8K3WXH5QXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60L90oBlyxNVeS5MPolNViQ5hQc4zYf4',
    appId: '1:761714459949:android:4e35759edf8aee8edeffa4',
    messagingSenderId: '761714459949',
    projectId: 'traveltovietnam-3270d',
    storageBucket: 'traveltovietnam-3270d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYVe_M4UrCnyNDpUMhERxJvuAZJYSf1c',
    appId: '1:761714459949:ios:08f4cbffb6ffa276deffa4',
    messagingSenderId: '761714459949',
    projectId: 'traveltovietnam-3270d',
    storageBucket: 'traveltovietnam-3270d.firebasestorage.app',
    iosBundleId: 'com.sportme.appnext2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYVe_M4UrCnyNDpUMhERxJvuAZJYSf1c',
    appId: '1:761714459949:ios:08f4cbffb6ffa276deffa4',
    messagingSenderId: '761714459949',
    projectId: 'traveltovietnam-3270d',
    storageBucket: 'traveltovietnam-3270d.firebasestorage.app',
    iosBundleId: 'com.sportme.appnext2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-gZcWdnKyw_3Xg1ozmDqPtTHiEG-wS3U',
    appId: '1:761714459949:web:2b849e78441e7100deffa4',
    messagingSenderId: '761714459949',
    projectId: 'traveltovietnam-3270d',
    authDomain: 'traveltovietnam-3270d.firebaseapp.com',
    storageBucket: 'traveltovietnam-3270d.firebasestorage.app',
    measurementId: 'G-PW4XN03R7X',
  );
}
